### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Disonantemus** [roguh/vis-backup#1]
I am no programmer and take a while until I get the plugin working, my problems was followings [README.md](https://github.com/roguh/vis-backup/blob/master/README.md):

Following instructions doesn't work:

- If the backup folder it's not created gives error, you need to clarify that it's mandatory.
- "Configuring backup path and backup filenames". Default backup folder is "~/.vis-backup" but LUA code says "~/.vis-backups"
- If I do "Save to another directory (with timestamp)", "Save to current directory (Emacs/Vim style)" get "attempt to index a nil value (global 'backup')" error, my fix was to change all "backup." to "module." and put the code inside "backup.lua" not "visrc.lua"

Hope this helps to someone.

**Comment by roguh** [comment]
Hi! Thanks for the feedback. I'll update the README and make sure it all still works correctly. Although I use `vis` regularly, especially to open enormous files or to do multi-line editing, I haven't checked in on my plugin's behavior in years. I install it automatically on most of my computers.

**Comment by roguh** [comment]
Ok, here's an updated README: https://github.com/roguh/vis-backup

I also added the `backup.set_directory` function that would create the directory if changing it, as well as `backup.create_directory`.

**Comment by roguh** [comment]
Also, let me know if I fixed your third point. I wasn't sure how to test that.
